version: '3.2'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    command: >
      bash -c '
        yum update -y
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']

  node01:
    container_name: node01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=node01 
      - cluster.name=bigdata-cluster
      - discovery.seed_hosts=node01,node02
      - cluster.initial_master_nodes=node01,node02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic 
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/node01/node01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/node01/node01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/node01/node01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/node01/node01.key
      - xpack.monitoring.collection.enabled=true
    volumes: ['data01:/usr/share/elasticsearch', 'certs:$CERTS_DIR', '.:/usr/share/elasticsearch/config/certificates']
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    depends_on: 
      - create_certs
    healthcheck:
      test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  node02:
    container_name: node02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=node02
      - cluster.name=bigdata-cluster      
      - discovery.seed_hosts=node01,node02
      - cluster.initial_master_nodes=node01,node02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/node02/node02.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/node02/node02.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/node02/node02.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/node02/node02.key
      - xpack.monitoring.collection.enabled=true
    volumes: ['data02:/usr/share/elasticsearch', 'certs:$CERTS_DIR']
    depends_on: 
      - create_certs
    networks:
      - elk

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana-ssl.yml:/usr/share/kibana/config/kibana.yml
      - certs:$CERTS_DIR
    ports:
      - "5601:5601"
    depends_on: 
      - create_certs
      - node01
    networks:
      - elk
  
  apm_server:
    container_name: apm_server
    build:
      context: APM/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./APM/config/apm-server-ssl.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - "8200:8200"
    restart: always
    networks:
      - elk

 # Metricbeat to optionally collect metrics from the entire setup; not required for logging itself
  metricbeat:
    hostname: metricbeat
    container_name: metricbeat
    user: root #To read the docker socket
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_STACK_VERSION}
    volumes:
      - certs:$CERTS_DIR
      # Bind-mount a custom configuration file
      - "./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      # Bind-mount the config directory so it can be dynamically loaded
      - "./metricbeat/config/:/usr/share/metricbeat/config/:ro"
      # Monitor the Docker host rather than the Metricbeat container; these are used by the system module
      - "/proc:/hostfs/proc:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/:/hostfs:ro"
      # Bind-mount the Docker daemon to enable add_docker_metadata from within the container
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: metricbeat -e
    restart: on-failure
    networks:
      - elk
    depends_on:
      - node01
      - kibana
   
  # Metricbeat to optionally collect metrics from the entire setup; not required for logging itself
  heartbeat:
    hostname: heartbeat
    container_name: heartbeat
    user: root #To read the docker socket
    image: docker.elastic.co/beats/heartbeat:${ELASTIC_STACK_VERSION}
    volumes:
      # Bind-mount a custom configuration file
      - "./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro"
      # Bind-mount the Docker daemon to enable add_docker_metadata from within the container
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: heartbeat -e
    restart: on-failure    
    networks:
      - elk
    depends_on:
      - node01
      - kibana

 # Filebeat collecting from a Docker container and sending to Elasticsearch
  filebeat_docker_for_elasticsearch:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    hostname: filebeat_docker_for_elasticsearch
    container_name: filebeat_docker_for_elasticsearch
    user: root #To read the docker socket
    volumes:
      # Bind-mount the Docker log directory from the Java container, so Filebeat can read its files
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      # Bind-mount a custom configuration file
      - "./filebeat/config/filebeat-docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      # Bind-mount the registry file to avoid data duplication between restarts
      #- "./docker-compose/filebeat-docker/registry/:/usr/share/filebeat/data/"
      # Bind-mount the Filebeat log file (not going to system out to avoid a logging loop)
      #- "./docker-compose/filebeat-docker/logs/:/usr/share/filebeat/logs/"
      # Bind-mount the Docker daemon to enable add_docker_metadata from within the container
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: filebeat
    restart: always    
    networks:
      - elk
    depends_on:
      - node01
      - kibana      

volumes: {"certs", "data01", "data02"}

networks:
  elk:
    driver: bridge

