---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "https://node01:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.apm.enabled: false
xpack.license_management.enabled: false
xpack.maps.enabled: false
xpack.canvas.enabled: false
xpack.logstash.enabled: false
xpack.cloud.enabled: false
xpack.uptime.enabled: false
xpack.beats.enabled: false
xpack.siem.enabled: false
xpack.infra.enabled: false
xpack.ml.enabled: false

## X-Pack security credentials
elasticsearch.ssl.verificationMode: none
elasticsearch.username: elastic
elasticsearch.password: B1gD@tA285gpWdfrt246

server.ssl.enabled: true
server.ssl.key: "/usr/share/elasticsearch/config/certificate/kibana/kibana.key"
server.ssl.certificate: "/usr/share/elasticsearch/config/certificate/kibana/kibana.crt"